# Estimating Vol

## 3. OHLC

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf
sns.set()

etf = yf.Ticker('SPY')
data = etf.history(start='2000-01-01', actions=False)
data.drop(['Volume'], inplace=True, axis=1)

data

                                 Open        High         Low       Close
Date
2000-01-03 00:00:00-05:00   95.094272   95.094272   92.287949   93.290207
2000-01-04 00:00:00-05:00   92.067432   92.408200   89.571810   89.641968
2000-01-05 00:00:00-05:00   89.762224   90.784528   88.038341   89.802315
2000-01-06 00:00:00-05:00   89.561741   90.764450   88.359032   88.359032
2000-01-07 00:00:00-05:00   90.002736   93.490593   89.842375   93.490593
...                               ...         ...         ...         ...
2024-08-27 00:00:00-04:00  559.489990  562.059998  558.320007  561.559998
2024-08-28 00:00:00-04:00  561.210022  561.650024  555.039978  558.299988
2024-08-29 00:00:00-04:00  560.309998  563.679993  557.179993  558.349976
2024-08-30 00:00:00-04:00  560.770020  564.200012  557.140015  563.679993
2024-09-03 00:00:00-04:00  560.469971  560.804993  549.530029  552.080017

[6206 rows x 4 columns]